<a href="https://colab.research.google.com/github/bnsimha/LLM-Course-Udemy/blob/main/part-1/tokens/ex_1_5_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
text = [ 'All that we are is the result of what we have thought',
         'To be or not to be that is the question',
         'Be yourself everyone else is already taken' ]

text[0]

'All that we are is the result of what we have thought'

In [2]:
import re

vocab = re.split(r'\s',text[0].lower())

vocab_spaced = [' ' + word for word in vocab if word]

In [3]:
print(' '.join(re.split(r'\s',text[0].lower())))

all that we are is the result of what we have thought


In [4]:
import re
vocab = re.split(r'\s',' '.join(text).lower())
vocab

['all',
 'that',
 'we',
 'are',
 'is',
 'the',
 'result',
 'of',
 'what',
 'we',
 'have',
 'thought',
 'to',
 'be',
 'or',
 'not',
 'to',
 'be',
 'that',
 'is',
 'the',
 'question',
 'be',
 'yourself',
 'everyone',
 'else',
 'is',
 'already',
 'taken']

In [5]:
vocab_new = sorted(set(vocab))
vocab_new

['all',
 'already',
 'are',
 'be',
 'else',
 'everyone',
 'have',
 'is',
 'not',
 'of',
 'or',
 'question',
 'result',
 'taken',
 'that',
 'the',
 'thought',
 'to',
 'we',
 'what',
 'yourself']

In [6]:
#encoder

word2idx = {}
for i,word in enumerate(vocab_new):
  word2idx[word] = i

In [7]:
#decoder

idx2word = {}
for i,word in enumerate(vocab_new):
  idx2word[i] = word

In [8]:
import numpy as np

ids = np.random.randint(0,len(vocab_new),size=5)
[ idx2word[id] for id in ids]

['that', 'question', 'of', 'is', 'yourself']

In [9]:
' '.join([ idx2word[id] for id in ids])

'that question of is yourself'

In [10]:
all_tokens = [word2idx[word] for word in vocab]

In [11]:
import re

text = [ 'All that we are is the result of what we have thought',
         'To be or not to be that is the question',
         'Be yourself everyone else is already taken' ]

all_words = re.split(r'\s',' '.join(text).lower())
vocab = sorted(set(all_words))

In [12]:
#encoder

text2idx = { text : id for id,text in enumerate(vocab)}

In [13]:
#decoder

idx2text = { id : text for id,text in enumerate(vocab)}

In [14]:
#wrapping up in funnctions

def encode(text):
  words = re.split(r'\s',text.lower())
  ids = [ text2idx[word] for word in words ]
  return ids

def decode(ids):
  words = [ idx2text[id] for id in ids ]
  text = ' '.join(words)
  return text

In [15]:
newtext = 'we already are the result of what ' \
          'everyone else already thought'
newtext_tokenIDs = encode(newtext)
decoded_text = decode(newtext_tokenIDs)

print('Original text:')
print(f'\t{newtext}')

print(f'\nToken IDs:')
print(f'\t{newtext_tokenIDs}')

print(f'\nDecoded text:')
print(f'\t{decoded_text}')

Original text:
	we already are the result of what everyone else already thought

Token IDs:
	[18, 1, 2, 15, 12, 9, 19, 5, 4, 1, 16]

Decoded text:
	we already are the result of what everyone else already thought


In [16]:
target_word = 'to'
target_id = text2idx[target_word]

full_text = ' '.join(text).lower()
words = re.split(r'\s', full_text)
idx = np.array([ text2idx[word] for word in words ])
index = np.where(idx == target_id)
final = [ words[max(0, t-1) : min(len(words), t+2)] for t in index[0] ]
string = [ ' '.join(f) for f in final ]
string

['thought to be', 'not to be']

In [17]:
#one-hot encoding
import numpy as np

encoding_matrix = np.zeros((len(all_words),len(vocab_new)),dtype=int)
for i,word in enumerate(all_words):
  encoding_matrix[i,text2idx[word]] = 1
print(f"shape = {encoding_matrix.shape}")
print(encoding_matrix)

shape = (29, 21)
[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 